### ISSUE TITLE
Returning an `AbstractSpace` object using `get_actions`

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#108] opened 2020-11-01 10:44 UTC
`get_actions` returns some sort of a "set" of all possible actions (both legal and illegal). This seems very much like the idea of returning a `Space` of all possible actions.

I was wondering if `get_actions` could return a `Space` object directly, as in, an instance of a subtype of `AbstractSpace`.

For discrete actions, presently we are fine returning just a collection of actions using `get_actions`. But for continuous actions, we won't be able to return something that enumerates over all continous actions and will need to return something like range of real numbers (or whatever is suitable in that context). Again, this is similar to the concept of returning an instance of a subtype of `AbstractSpace`.

This will also allow us to categorize environments based on a useful taxonomy for environments (derived from the types of their action spaces). One (far-fetched) use-case that comes to my mind is some sort of automated dispatch on a suitable type of algorithm depending upon the type of environment. And algorithmic techniques ofter depend upon the kinds of action spaces (discrete vs. continous, for example).

**Comment by findmyway** [comment] 2020-12-16 04:33
Addressed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/110

In the current solution, the return of `action_space` can be of:

- Collection
- Interval
- Space(collections/intervals)
- WorldSpace() # a dummy one
- Any other customized one which supports
  - Random.rand
  - Base.in

**Closed by findmyway** 2020-12-16 04:33 UTC
Labels: RLBase

**Comment by konmeso** [comment] 2022-04-17 12:17
Hello guys, can you check out this issue please? 
https://stackoverflow.com/questions/71901031/multidimensional-action-space-in-reinforcement-learning-julia

I have really been struggling with how the spaces should be defined. The environment of the issue is based on the MountainCarEnv.

**Comment by findmyway** [comment] 2022-04-17 14:59
Hi @konmeso ,

I replied there. Hope it helps. Let me know if you still have problems.
