### ISSUE TITLE
params() is no longer supported in Flux

### ISSUE THREAD

**Issue by halyusuf25** [JuliaReinforcementLearning/ReinforcementLearning.jl#996] opened 2023-10-24 17:49 UTC
When trying to run any example experiment with neural net i got the following error:
 ERROR: UndefVarError: `params` not defined
 
 tracing back the error and found that it always come from the Flux function params, for example when running the JuliaRL_BCQD_CartPole.jl experiment the error comes from neural_network_approximator object and more specifically from this function 
`function Base.copyto!(dest::ActorCritic, src::ActorCritic)
    Flux.loadparams!(dest.actor, params(src.actor))
    Flux.loadparams!(dest.critic, params(src.critic))
end`

After some google search i found that params() function was supported in Flux <= version 0.12 but it was removed in version 0.13
https://fluxml.ai/Flux.jl/stable/training/reference/#Flux.params
i tried "using Flux: params" but it gives me the same error...

im creating this issue because this change is impacting almost all experiments examples.

**Comment by HenriDeh** [comment] 2023-10-25 08:08
I'm closing since this is a duplicate of #982

**Closed by HenriDeh** 2023-10-25 08:08 UTC
