### ISSUE TITLE
Julia 1.6.0 dependency problem with `ReinforcementLearningBase`/RLBase

### ISSUE THREAD

**Issue by emsal1863** [JuliaReinforcementLearning/ReinforcementLearning.jl#221] opened 2021-03-28 14:44 UTC
After updating to Julia 1.6, I'm getting the following warnings when trying to import the package. 

```
julia> using ReinforcementLearning
[ Info: Precompiling ReinforcementLearning [158674fc-8238-5cab-b5ba-03dfc80d1318]
┌ Warning: Package ReinforcementLearning does not have Dates in its dependencies:
│ - If you have ReinforcementLearning checked out for development and have
│   added Dates as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ReinforcementLearning
└ Loading Dates into ReinforcementLearning from project dependency, future warnings for ReinforcementLearning are suppressed.
WARNING: could not import ReinforcementLearningBase.interact! into ReinforcementLearning
WARNING: could not import ReinforcementLearningBase.getstate into ReinforcementLearning
WARNING: could not import ReinforcementLearningBase.plotenv into ReinforcementLearning
WARNING: could not import ReinforcementLearningBase.actionspace into ReinforcementLearning
WARNING: could not import ReinforcementLearningBase.sample into ReinforcementLearning
```

When trying to define a custom environment this is essentially breaking. Trying to `add ReinforcementLearningBase` separately results in more dependency problems.

**Comment by findmyway** [comment] 2021-03-29 03:09
Hi @emsal1863 ,

I just did a quick test and I can't reproduce the warning you posted above. Could you try again with `] activate --temp` ?

**Comment by emsal1863** [comment] 2021-03-29 17:31
This is actually a different issue. When trying to update `ReinforcementLearning` with 1.6 I get a dependency problem with the following log:

```
(@v1.6) pkg> add ReinforcementLearning@0.8.0
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GeometricFlux [7e08b658]:
 GeometricFlux [7e08b658] log:
 ├─possible versions are: 0.1.0-0.7.5 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.7.5
 ├─restricted by julia compatibility requirements to versions: [0.1.0-0.6.1, 0.7.5] or uninstalled, leaving only versions: [0.1.0-0.6.1, 0.7.5]
 ├─restricted by compatibility requirements with CuArrays [3a865a2d] to versions: [0.1.0-0.2.0, 0.6.1-0.7.5] or uninstalled, leaving only versions: [0.1.0-0.2.0, 0.6.1, 0.7.5]
 │ └─CuArrays [3a865a2d] log:
 │   ├─possible versions are: 0.2.1-2.2.2 or uninstalled
 │   └─restricted by julia compatibility requirements to versions: uninstalled
 ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.1.0-0.6.0 or uninstalled, leaving only versions: 0.1.0-0.2.0
 │ └─CUDA [052768ef] log:
 │   ├─possible versions are: 0.1.0-2.6.2 or uninstalled
 │   ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-2.6.2] or uninstalled
 │   └─restricted by compatibility requirements with ReinforcementLearningZoo [d607f57d] to versions: [1.0.0-1.3.3, 2.1.0-2.6.2], leaving only versions: [2.3.0, 2.5.0-2.6.2]
 │     └─ReinforcementLearningZoo [d607f57d] log:
 │       ├─possible versions are: 0.1.0-0.3.4 or uninstalled
 │       └─restricted by compatibility requirements with ReinforcementLearning [158674fc] to versions: 0.3.0-0.3.4
 │         └─ReinforcementLearning [158674fc] log:
 │           ├─possible versions are: 0.2.0-0.8.0 or uninstalled
 │           └─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.0
 ├─restricted by compatibility requirements with CUDAapi [3895d2a7] to versions: [0.1.0-0.1.1, 0.6.1-0.7.5] or uninstalled, leaving only versions: 0.1.0-0.1.1
 │ └─CUDAapi [3895d2a7] log:
 │   ├─possible versions are: 0.5.0-4.0.0 or uninstalled
 │   └─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with Requires [ae029012] to versions: 0.3.0-0.7.5 or uninstalled — no versions left
   └─Requires [ae029012] log:
     ├─possible versions are: 0.5.0-1.1.3 or uninstalled
     ├─restricted by compatibility requirements with GeometricFlux [7e08b658] to versions: 0.5.0-1.1.3
     │ └─GeometricFlux [7e08b658] log: see above
     └─restricted by compatibility requirements with ReinforcementLearningZoo [d607f57d] to versions: 1.0.0-1.1.3
       └─ReinforcementLearningZoo [d607f57d] log: see above
```

**Comment by findmyway** [comment] 2021-03-30 02:02
Based on the log, it seems GeometricFlux.jl needs to be updated to support the latest CUDA.jl.

Tagging @yuehhua to confirm it.

**Comment by yuehhua** [comment] 2021-03-31 13:11
Yeah, I will update it soon!

**Comment by yuehhua** [comment] 2021-04-05 23:46
@findmyway @emsal1863 Should be fixed now.

**Comment by findmyway** [comment] 2021-04-06 01:25
Thanks!

**Closed by findmyway** 2021-04-06 01:25 UTC
