### ISSUE TITLE
Fails to load trajectory

### ISSUE THREAD

**Issue by oysteinsolheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#150] opened 2020-11-22 17:53 UTC
The following fails:
```
using ReinforcementLearning
using JLD

t = CircularCompactSARTSATrajectory(; capacity=3)
JLD.save("trajectory.jld", "t", t)
t = JLD.load("trajectory.jld", "t")
```

with
```
ERROR: stored type ReinforcementLearningCore.CombinedTrajectory{ReinforcementLearningCore.Trajectory{Core.NamedTuple{(:reward, :terminal),Core.Tuple{ReinforcementLearningCore.CircularArrayBuffer{Core.Float32,1},ReinforcementLearningCore.CircularArrayBuffer{Core.Bool,1}}}},ReinforcementLearningCore.CombinedTrajectory{ReinforcementLearningCore.SharedTrajectory{ReinforcementLearningCore.CircularArrayBuffer{Core.Int64,1},Core.NamedTuple{(:state, :next_state, :full_state),Core.Tuple{ReinforcementLearningCore.SharedTrajectoryMeta,ReinforcementLearningCore.SharedTrajectoryMeta,ReinforcementLearningCore.SharedTrajectoryMeta}}},ReinforcementLearningCore.SharedTrajectory{ReinforcementLearningCore.CircularArrayBuffer{Core.Int64,1},Core.NamedTuple{(:action, :next_action, :full_action),Core.Tuple{ReinforcementLearningCore.SharedTrajectoryMeta,ReinforcementLearningCore.SharedTrajectoryMeta,ReinforcementLearningCore.SharedTrajectoryMeta}}}}} does not match currently loaded type
```
I noticed this first in the save-function in agent.jl line 61
https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/components/agents/agent.jl

**Comment by findmyway** [comment] 2020-11-23 00:04
Hi @oysteinsolheim ,

It might be that the type is too complex. I'll take a look at it and see if there're other alternatives.

**Comment by findmyway** [comment] 2020-11-23 09:54
Strange, I can't reproduce this error. I'm using `JLD@v0.10.0` and `ReinforcementLearningCore@v0.5.1`. Could you share which packages are you using?

**Comment by oysteinsolheim** [comment] 2020-11-23 10:26
julia> versioninfo()
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 12

(traj_test) pkg> st
Status `~/JuliaProjects/traj_test/Project.toml`
  [4138dd39] JLD v0.10.0
  [158674fc] ReinforcementLearning v0.7.0
```

**Comment by oysteinsolheim** [comment] 2020-11-23 11:28
To me it seems like the issue is connected to the version of HDF5. If I am installing ReinforcementLearning first, the version of HFD5 is set to v0.13.6. However, if installing JLD first or manually updating to the latest version of HDF5, v0.13.7 - it works!

**Comment by findmyway** [comment] 2020-11-23 14:44
I just did a quick test and confirmed your analysis.

Now sure why we get the below downgrading:

```julia
(test) pkg> add HDF5@v0.13.7
  Resolving package versions...
Updating `/mnt/E4E0A9C0E0A998F6/github/test/Project.toml`
  [f67ccb44] ↑ HDF5 v0.13.6 ⇒ v0.13.7
Updating `/mnt/E4E0A9C0E0A998F6/github/test/Manifest.toml`
  [f67ccb44] ↑ HDF5 v0.13.6 ⇒ v0.13.7
  [0234f1f7] ↓ HDF5_jll v1.12.0+1 ⇒ v1.10.5+7
  [deac9b47] - LibCURL_jll v7.70.0+2
  [29816b5a] - LibSSH2_jll v1.9.0+3
  [458c3c95] - OpenSSL_jll v1.1.1+6
  [8e850ede] - nghttp2_jll v1.40.0+2
```

I guess things will be fixed once https://github.com/JuliaIO/JLD.jl/pull/280 gets merged.

Let's keep this issue open and update the `compat` section in the next JLD release.

**Comment by findmyway** [comment] 2020-12-03 14:35
I'm closing this issue given that load/save related functions are removed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/169

**Closed by findmyway** 2020-12-03 14:35 UTC
Labels: RLCore, bug, regression
